---
title: "Find best hyperparameter"
output: html_notebook
---

```{r}
library(dplyr)
library(prophet)
library(plotly)
```

```{r}
path <- "../data/tuning_result.csv"
tuning_result <- read.csv(path)

tuning_result
```

```{r}
path <- "../data/alcohol_sales.csv"

df <- read.csv(path,
               na.strings = c("null", ".", ""))
df <- df %>%
  rename(ds = Date,
         y = Sale) %>%
  mutate(ds = as.Date(ds,
                      format = "%Y-%m-%d"))

df
```

```{r}
split_date <- "2017-12-01"
train <- df[df$ds <= split_date,]
test <- df[df$ds > split_date,]

test
```

```{r}
index <- tuning_result %>%
  select(mse,
         mae,
         mape) %>%
  apply(MARGIN = 2,
        which.min) %>%
  unique()

best_parameters <- tuning_result[index, ]
row.names(best_parameters) <- NULL

best_parameters
```

Use hypterparameters with 80% $changepoint.range$ because This is fairly conservative, to avoid overfitting to trend changes at the very end of the time series.

```{r}
m <- prophet(
  train,
  yearly.seasonality = TRUE,
  weekly.seasonality = FALSE,
  daily.seasonality = FALSE,
  changepoint.prior.scale = best_parameters[1, ]$changepoint_prior_scale,
  seasonality.prior.scale = best_parameters[1, ]$seasonality_prior_scale,
  holidays.prior.scale = best_parameters[1, ]$holidays_prior_scale,
  seasonality.mode = best_parameters[1, ]$seasonality_mode,
  changepoint.range = best_parameters[1, ]$changepoint_range
)

pred <- predict(m, test)
pred <- pred %>%
  mutate(ds = as.Date(ds,
                      format = "%Y-%m-%d")) %>%
  select(ds,
         yhat)

forecast <- df %>%
  full_join(pred,
            by = "ds")

tail(forecast)
```

```{r}
fig <- plot_ly(
  forecast,
  x = ~ ds,
  y = ~ y,
  name = "Actual",
  type = "scatter",
  mode = "lines",
  line = list(color = "rgba(49,130,189,1)")
)
fig <- fig %>%
  add_trace(
    y = ~ yhat,
    name = "Forecast",
    line = list(color = "rgba(230,0,0,1)")
  )

fig <- fig %>%
  layout(
    title = "Alcohol sales forecast form Jan 2018 to Jan 2019",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Sale")
  )

fig
```