---
title: "R Notebook"
output: html_notebook
---

```{r}
library(plotly)
library(tidyverse)
library(xts)
library(tseries)
```


```{r}
path <- "C:\\__MeineDaten\\EthereumForecast\\data\\eth_data.csv"
df <- read.csv(path, na.strings = c("null",".",""))

colSums(
  is.na(df)
  )
```
```{r}
num_cols <- subset(df, select = -c(Date))
apply(num_cols,
      MARGIN = 2,
      function(x) which(
        is.na(
          as.numeric(
            as.character(x)
            )
          )
        )
      )
```


```{r}
fig <- plot_ly(
  df,
  x = ~ Date,
  y = ~ Open,
  name="Price",
  type = "scatter",
  mode = "lines",
  line = list(
      color = "rgba(49,130,189,1)"
      )
  )

fig <- fig %>%
  add_trace(
    y = ~High,
    name="Max. price",
    line = list(
      color = "rgba(49,130,189,0.5)"
      )
  )

fig <- fig %>%
  add_trace(
    y = ~Low,
    name="Min. price",
    line = list(
      color = "rgba(49,130,189,0.5)"
      ) 
  )

fig <- fig %>%
  layout(
    title = "History of daily prices of Ethereum",
    xaxis = list(type = "date"),
    yaxis = list(type = "linear", title="Close Price in USD")
    )

fig
```


```{r}
time_series <- df %>%
  select(
    Date,
    Open
    ) %>%
  replace_na(
    list(
      Date = 0,
      Open = 0
      )
    )

time_series <- xts(
  time_series$Open,
  as.Date(
    time_series$Date,
    format="%Y-%m-%d"
    )
  )

adf.test(time_series)
# time series is non-stationary
```

