---
title: "Exploratory Data Analysis"
output: html_notebook
---

```{r warning=FALSE, echo=FALSE, message=FALSE}
library(plotly)
library(dplyr)
library(xts)
library(zoo)
library(tseries)
```

```{r}
path <- "../data/alcohol_sales.csv"

df <- read.csv(path, na.strings = c("null", ".", ""))
df <- df %>%
  mutate(Date = as.Date(Date, format = "%Y-%m-%d"))

df
```

```{r}
missing_values <- apply(df,
                        MARGIN = 2,
                        function(x)
                          which(is.na(x)))

if (length(missing_values) == 0) {
  print("No missing values")
} else {
  print("Indexes missing values")
  print(missing_values)
}
```

```{r}

rsd <- rollapply(df$Sale,
                 width = 12,
                 FUN = sd,
                 fill = NA)

rmean <- rollapply(df$Sale,
                   width = 12,
                   FUN = mean,
                   fill = NA)

fig <- plot_ly(
  df,
  x = ~ Date,
  y = ~ Sale,
  name = "Actual",
  type = "scatter",
  mode = "lines",
  line = list(color = "rgba(49,130,189,1)")
)
fig <- fig %>%
  add_trace(
    y = rmean,
    name = "Moving Average",
    line = list(color = "rgba(230,0,0,1)")
  )
fig <- fig %>%
  add_trace(
    y = rmean + rsd,
    name = "Moving Average + 1 Std",
    line = list(color = "rgba(0,230,0,1)")
  )

fig <- fig %>%
  add_trace(
    y = rmean - rsd,
    name = "Moving Average - 1 Std",
    line = list(color = "rgba(100,30,230,1)")
  )

fig <- fig %>%
  layout(title = "Alcohol Sales form Jan 1992 to Jan 2019")

fig
```
As seen from the above plot, the standard deviation is not varying much so there is not much variance.

```{r}
ts <- xts(df$Sale,
          as.Date(df$Date,
                  format = "%Y-%m-%d"))

adft <- adf.test(ts, k = 12)

if (adft$p.value <= 0.05) {
  print("Reject null hypothesis, data is stationary")
  print(paste("p-value:", adft$p.value))
} else {
  print("Do not reject null hypothesis, data is not stationary")
  print(paste("p-value:", adft$p.value))
}
```

```{r}
acf(ts, main="")

```
```{r}
pacf(ts, main="")
```






